<?php
use GDI\Dominio\Personas\Domicilio;
use GDI\Dominio\Personas\EntidadFederativa;
use GDI\Dominio\Polizas\AsociadoProtegido;

class PersonasTest extends PHPUnit_Framework_TestCase
{
    protected $persona;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->persona = new AsociadoProtegido(0, '', 'GORG', new Domicilio('AV. BARRIO COLÓN', '261', '', 'FRACC. DIAMANTES RESIDENCIAL', '29059', 'TUXTLA GUTIÉRREZ', new EntidadFederativa()));
    }

    public function testDevuelveElDomicilioDeManeraCorrecta()
    {
        $domicilio = 'AV. BARRIO COLÓN 261 FRACC. DIAMANTES RESIDENCIAL C. P. 29059 TUXTLA GUTIÉRREZ, CHIAPAS';

        $this->assertEquals($domicilio, $this->persona->getDomicilio()->direccionCompleta());
    }
}