<?php

namespace DoctrineProxies\__CG__\GDI\Dominio\Vehiculos;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Vehiculo extends \GDI\Dominio\Vehiculos\Vehiculo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'id', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'modelo', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'anio', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'numeroSerie', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'numeroMotor', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'placas', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'capacidad', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'modalidad', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'servicio', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'asociadoProtegido', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'oficina'];
        }

        return ['__isInitialized__', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'id', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'modelo', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'anio', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'numeroSerie', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'numeroMotor', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'placas', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'capacidad', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'modalidad', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'servicio', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'asociadoProtegido', '' . "\0" . 'GDI\\Dominio\\Vehiculos\\Vehiculo' . "\0" . 'oficina'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Vehiculo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getModelo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModelo', []);

        return parent::getModelo();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnio', []);

        return parent::getAnio();
    }

    /**
     * {@inheritDoc}
     */
    public function getModalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModalidad', []);

        return parent::getModalidad();
    }

    /**
     * {@inheritDoc}
     */
    public function getAsociadoProtegido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsociadoProtegido', []);

        return parent::getAsociadoProtegido();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroSerie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroSerie', []);

        return parent::getNumeroSerie();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroMotor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroMotor', []);

        return parent::getNumeroMotor();
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidad', []);

        return parent::getCapacidad();
    }

    /**
     * {@inheritDoc}
     */
    public function getOficina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOficina', []);

        return parent::getOficina();
    }

    /**
     * {@inheritDoc}
     */
    public function getServicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServicio', []);

        return parent::getServicio();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlacas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlacas', []);

        return parent::getPlacas();
    }

    /**
     * {@inheritDoc}
     */
    public function detalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'detalles', []);

        return parent::detalles();
    }

}
