<?php

namespace DoctrineProxies\__CG__\GDI\Dominio\Polizas;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AsociadoAgente extends \GDI\Dominio\Polizas\AsociadoAgente implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'id', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'rfc', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'porcentajeComision', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'reciboHonorarios', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'domicilio', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'oficina', 'nombre', 'paterno', 'materno', 'sexo', 'telefono', 'celular', 'email'];
        }

        return ['__isInitialized__', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'id', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'rfc', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'porcentajeComision', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'reciboHonorarios', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'domicilio', '' . "\0" . 'GDI\\Dominio\\Polizas\\AsociadoAgente' . "\0" . 'oficina', 'nombre', 'paterno', 'materno', 'sexo', 'telefono', 'celular', 'email'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AsociadoAgente $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getRfc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRfc', []);

        return parent::getRfc();
    }

    /**
     * {@inheritDoc}
     */
    public function getPorcentajeComision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPorcentajeComision', []);

        return parent::getPorcentajeComision();
    }

    /**
     * {@inheritDoc}
     */
    public function reciboHonorarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'reciboHonorarios', []);

        return parent::reciboHonorarios();
    }

    /**
     * {@inheritDoc}
     */
    public function getDomicilio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomicilio', []);

        return parent::getDomicilio();
    }

    /**
     * {@inheritDoc}
     */
    public function getOficina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOficina', []);

        return parent::getOficina();
    }

    /**
     * {@inheritDoc}
     */
    public function generar($nombreAgente, $paternoAgente, $maternoAgente, \GDI\Dominio\Personas\Domicilio $domicilio, \GDI\Dominio\Oficinas\Oficina $oficina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generar', [$nombreAgente, $paternoAgente, $maternoAgente, $domicilio, $oficina]);

        return parent::generar($nombreAgente, $paternoAgente, $maternoAgente, $domicilio, $oficina);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function getPaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaterno', []);

        return parent::getPaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function getMaterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaterno', []);

        return parent::getMaterno();
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function getCelular()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCelular', []);

        return parent::getCelular();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function nombreCompleto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nombreCompleto', []);

        return parent::nombreCompleto();
    }

}
